### PR TITLE
Fix KDoc link to context parameter

### LINKED ISSUE #4389: Dokka 2.1.0 crashes with context parametered properties
This code:
```kotlin
/**
 * The default value for [this] component type within this [ecs], overruling [Entity.default].
 *
 * @since 0.0.1-alpha.4
 */
context(ecs: Ecs)
public val <T> Entity<T>.currentDefault: T get() = ecs.getDefaultOf(this)

/**
 * The default value for [this] component type within this [ecs], overruling [Entity.default].
 *
 * @since 0.0.1-alpha.4
 */
@Suppress("CONTEXTUAL_OVERLOAD_SHADOWED") // same behavior
context(ecs: MutableEcs)
public var <T> Entity<T>.currentDefault: T
    get() = ecs.getDefaultOf(this)
    set(value) = ecs.setDefaultOf(this, value)
```

Where `MutableEcs` extends `Ecs`, crashes with this error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:dokkaGenerateModuleHtml'.
> A failure occurred while executing org.jetbrains.dokka.gradle.workers.DokkaGeneratorWorker
   > Error in translating of symbol (currentDefault) org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirKotlinPropertyKtPropertyBasedSymbol@68f58c51 in file: /home/admin/.projects/spock/core/src/commonMain/kotlin/EcsDsl.kt, (1198,1419)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to generate a Build Scan (powered by Develocity).
> Get more help at https://help.gradle.org.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':core:dokkaGenerateModuleHtml'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:288)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:133)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.api.internal.tasks.execution.ProblemsTaskPathTrackingTaskExecuter.execute(ProblemsTaskPathTrackingTaskExecuter.java:41)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.DefaultNodeExecutor.executeLocalTaskNode(DefaultNodeExecutor.java:55)
	at org.gradle.execution.plan.DefaultNodeExecutor.execute(DefaultNodeExecutor.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.lambda$execute$0(DefaultTaskExecutionGraph.java:339)
	at org.gradle.internal.operations.CurrentBuildOperationRef.with(CurrentBuildOperationRef.java:84)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:339)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:328)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:459)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:376)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: org.gradle.workers.internal.DefaultWorkerExecutor$WorkExecutionException: A failure occurred while executing org.jetbrains.dokka.gradle.workers.DokkaGeneratorWorker
	at org.gradle.workers.internal.DefaultWorkerExecutor$WorkItemExecution.waitForCompletion(DefaultWorkerExecutor.java:289)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.lambda$waitForItemsAndGatherFailures$2(DefaultAsyncWorkTracker.java:130)
	at org.gradle.internal.Factories$1.create(Factories.java:33)
	at org.gradle.internal.work.DefaultWorkerLeaseService.lambda$withoutLocks$2(DefaultWorkerLeaseService.java:344)
	at org.gradle.internal.work.ResourceLockStatistics$1.measure(ResourceLockStatistics.java:42)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:342)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLocks(DefaultWorkerLeaseService.java:326)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withoutLock(DefaultWorkerLeaseService.java:331)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:126)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForItemsAndGatherFailures(DefaultAsyncWorkTracker.java:92)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForAll(DefaultAsyncWorkTracker.java:78)
	at org.gradle.internal.work.DefaultAsyncWorkTracker.waitForCompletion(DefaultAsyncWorkTracker.java:66)
	at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:260)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.run(DefaultBuildOperationRunner.java:47)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeAction(TaskExecution.java:237)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeActions(TaskExecution.java:220)
	at org.gradle.api.internal.tasks.execution.TaskExecution.executeWithPreviousOutputFiles(TaskExecution.java:203)
	at org.gradle.api.internal.tasks.execution.TaskExecution.execute(TaskExecution.java:170)
	at org.gradle.internal.execution.steps.ExecuteStep.executeInternal(ExecuteStep.java:105)
	at org.gradle.internal.execution.steps.ExecuteStep.access$000(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:59)
	at org.gradle.internal.execution.steps.ExecuteStep$1.call(ExecuteStep.java:56)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:209)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:166)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:56)
	at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:44)
	at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:42)
	at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:75)
	at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:55)
	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:50)
	at org.gradle.internal.execution.steps.PreCreateOutputParentsStep.execute(PreCreateOutputParentsStep.java:28)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:68)
	at org.gradle.internal.execution.steps.RemovePreviousOutputsStep.execute(RemovePreviousOutputsStep.java:38)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:61)
	at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:26)
	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:69)
	at org.gradle.internal.execution.steps.CaptureOutputsAfterExecutionStep.execute(CaptureOutputsAfterExecutionStep.java:46)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:39)
	at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:28)
	at org.gradle.internal.execution.steps.BuildCacheStep.executeWithoutCache(BuildCacheStep.java:189)
	at org.gradle.internal.execution.steps.BuildCacheStep.lambda$execute$1(BuildCacheStep.java:75)
	at org.gradle.internal.Either$Right.fold(Either.java:176)
	at org.gradle.internal.execution.caching.CachingState.fold(CachingState.java:62)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:73)
	at org.gradle.internal.execution.steps.BuildCacheStep.execute(BuildCacheStep.java:48)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:46)
	at org.gradle.internal.execution.steps.StoreExecutionStateStep.execute(StoreExecutionStateStep.java:35)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:75)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$2(SkipUpToDateStep.java:53)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:53)
	at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:35)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:37)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:27)
	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:49)
	at org.gradle.internal.execution.steps.ResolveIncrementalCachingStateStep.executeDelegate(ResolveIncrementalCachingStateStep.java:27)
	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:71)
	at org.gradle.internal.execution.steps.AbstractResolveCachingStateStep.execute(AbstractResolveCachingStateStep.java:39)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:64)
	at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:35)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:62)
	at org.gradle.internal.execution.steps.ValidateStep.execute(ValidateStep.java:40)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:76)
	at org.gradle.internal.execution.steps.AbstractCaptureStateBeforeExecutionStep.execute(AbstractCaptureStateBeforeExecutionStep.java:45)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.executeWithNonEmptySources(AbstractSkipEmptyWorkStep.java:136)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:61)
	at org.gradle.internal.execution.steps.AbstractSkipEmptyWorkStep.execute(AbstractSkipEmptyWorkStep.java:38)
	at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsStartedStep.execute(MarkSnapshottingInputsStartedStep.java:38)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:36)
	at org.gradle.internal.execution.steps.LoadPreviousExecutionStateStep.execute(LoadPreviousExecutionStateStep.java:23)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:75)
	at org.gradle.internal.execution.steps.HandleStaleOutputsStep.execute(HandleStaleOutputsStep.java:41)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.lambda$execute$0(AssignMutableWorkspaceStep.java:35)
	at org.gradle.api.internal.tasks.execution.TaskExecution$4.withWorkspace(TaskExecution.java:297)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:31)
	at org.gradle.internal.execution.steps.AssignMutableWorkspaceStep.execute(AssignMutableWorkspaceStep.java:22)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:40)
	at org.gradle.internal.execution.steps.ChoosePipelineStep.execute(ChoosePipelineStep.java:23)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.lambda$execute$2(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:67)
	at org.gradle.internal.execution.steps.ExecuteWorkBuildOperationFiringStep.execute(ExecuteWorkBuildOperationFiringStep.java:39)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:46)
	at org.gradle.internal.execution.steps.IdentityCacheStep.execute(IdentityCacheStep.java:34)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:44)
	at org.gradle.internal.execution.steps.IdentifyStep.execute(IdentifyStep.java:31)
	at org.gradle.internal.execution.impl.DefaultExecutionEngine$1.execute(DefaultExecutionEngine.java:64)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:132)
	... 30 more
Caused by: org.jetbrains.dokka.analysis.kotlin.symbols.translators.TranslatorError: Error in translating of symbol (currentDefault) org.jetbrains.kotlin.analysis.api.fir.symbols.KaFirKotlinPropertyKtPropertyBasedSymbol@68f58c51 in file: /home/admin/.projects/spock/core/src/commonMain/kotlin/EcsDsl.kt, (1198,1419)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.visitPropertySymbol(DefaultSymbolToDocumentableTranslator.kt:1317)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.visitPackageSymbol(DefaultSymbolToDocumentableTranslator.kt:131)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.access$visitPackageSymbol(DefaultSymbolToDocumentableTranslator.kt:77)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.visitModule(DefaultSymbolToDocumentableTranslator.kt:107)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DefaultSymbolToDocumentableTranslator.invokeSuspending(DefaultSymbolToDocumentableTranslator.kt:61)
	at org.jetbrains.dokka.base.generation.SingleModuleGeneration$translateSources$$inlined$parallelMap$1$1.invokeSuspend(parallelCollectionOperations.kt:17)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
Caused by: java.lang.IllegalStateException: Can not get callable Id due to it is local
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DRIFactoryKt.getDRIFromVariable(DRIFactory.kt:66)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DRIFactoryKt.getDRIFromSymbol(DRIFactory.kt:124)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.ResolveKDocLinkKt.resolveKDocLinkToDRI(ResolveKDocLink.kt:124)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KDocProviderKt.getKDocDocumentationFrom$lambda$6$lambda$5(KDocProvider.kt:69)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KdocMarkdownParserKt.parseFromKDocTag$lambda$4$lambda$2(KdocMarkdownParser.kt:43)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.resolveDRI(MarkdownParser.kt:206)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.linksHandler(MarkdownParser.kt:259)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.linksHandler$default(MarkdownParser.kt:258)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.referenceLinksHandler(MarkdownParser.kt:229)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.visitNode(MarkdownParser.kt:424)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.evaluateChildren(MarkdownParser.kt:460)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:459)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.defaultHandler(MarkdownParser.kt:406)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.visitNode(MarkdownParser.kt:450)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.evaluateChildren(MarkdownParser.kt:460)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.evaluateChildren$default(MarkdownParser.kt:459)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.markdownFileHandler(MarkdownParser.kt:249)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.visitNode(MarkdownParser.kt:444)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.visitNode$default(MarkdownParser.kt:409)
	at org.jetbrains.dokka.analysis.markdown.jb.MarkdownParser.parseStringToDocNode(MarkdownParser.kt:41)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KdocMarkdownParserKt.parseFromKDocTag$parseStringToDocNode(KdocMarkdownParser.kt:30)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KdocMarkdownParserKt.parseFromKDocTag(KdocMarkdownParser.kt:46)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KdocMarkdownParserKt.parseFromKDocTag$default(KdocMarkdownParser.kt:20)
	at org.jetbrains.dokka.analysis.kotlin.symbols.kdoc.KDocProviderKt.getKDocDocumentationFrom(KDocProvider.kt:67)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.getDocumentation(DefaultSymbolToDocumentableTranslator.kt:893)
	at org.jetbrains.dokka.analysis.kotlin.symbols.translators.DokkaSymbolVisitor.visitPropertySymbol(DefaultSymbolToDocumentableTranslator.kt:513)
	... 7 more


BUILD FAILED in 11s
```

### PR DESCRIPTION
**Pull request by vmishenev**
fixes #4389

### CODE REVIEW

File: dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt [hunk 1]
```diff
@@ -118,10 +128,13 @@ private fun KaSession.getDRIFromReceiverType(type: KaType): DRI {
 internal fun KaSession.getDRIFromSymbol(symbol: KaSymbol): DRI =
     when (symbol) {
         is KaEnumEntrySymbol -> getDRIFromEnumEntry(symbol)
-        is KaReceiverParameterSymbol -> getDRIFromReceiverParameter(symbol)
+        is KaParameterSymbol -> @OptIn(KaExperimentalApi::class) when (symbol) {
+            is KaReceiverParameterSymbol -> getDRIFromReceiverParameter(symbol)
+            is KaValueParameterSymbol -> getDRIFromValueParameter(symbol)
+            is KaContextParameterSymbol -> getDRIFromContextParameter(symbol)
```
Comment (whyoleg) [inline dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt]: TBH, I don't understand why handling the context parameters symbol here will fix the reported issue.

I mean, in the reported issue, we throw `java.lang.IllegalStateException: Can not get callable Id due to it is local` from inside `getDRIFromVariable`, but this branch is still there, so I would expect that the same error will happen.
Or I'm missing something?

Comment (vmishenev) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt]: Before the change,  the `KaVariableSymbol -> getDRIFromVariable(symbol)` branch is triggered because `KaContextParameterSymbol` extends `KaVariableSymbol`.

Comment (whyoleg) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DRIFactory.kt]: Ah, now I see, thanks!

Maybe it makes sense then to use exhaustive `when` for all sealed hierarchies of symbols?
e.g., like this:
```kotlin
when (symbol) {
    is KaCallableSymbol -> when (symbol) {
        is KaVariableSymbol -> when (symbol) {
            is KaParameterSymbol -> when (symbol) {
                is KaContextParameterSymbol -> TODO()
                is KaReceiverParameterSymbol -> TODO()
                is KaValueParameterSymbol -> TODO()
            }
            // is A, is B -> ...
        }

```
