### PR TITLE
Fix DGP reading all Gradle properties

### LINKED ISSUE #4467: DGP reads all Gradle properties, which causes unnecessary CC invalidation
Replace `.provider { project.extra.properties[flag]?.toString() }` with `.provider { project.findProperty(flag)?.toString() }`

https://github.com/Kotlin/dokka/blob/v2.2.0-Beta/dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt#L341

Add a CC reuse test where (using Gradle 9.1 or 9.4-rc-1) you change a unused property but the cache is reused. (Keep in mind Gradle 9.2 and 9.3 had a regression and any Gradle property change would invalidate CC.)

Context:
DGP uses a Gradle property to toggle between v1 and v2 modes. There are a lot of unit tests for this. The tests use Gradle's ProjectBuilder, not TestKit, because it's much faster. But ProjectBuilder doesn't support mocking Gradle properties - instead the tests use extra properties.

---

Plan:

- Update Dokka's Gradle to 9.1 (currently it's 8.14.2).
- Move `dokka-integration-tests/gradle/src/main/kotlin/org/jetbrains/dokka/it/gradle/gradleCCReportData.kt` to `dokka-runners/dokka-gradle-plugin/src/testFixtures/kotlin/`. 
- Create a test in `dokka-runners/dokka-gradle-plugin/src/testFunctional/kotlin/`.

### PR DESCRIPTION
**Pull request by adam-enko**
- Replace `project.extra.properties[...]` (which reads all properties, meaning they will be CC inputs) with `project.findProperty(...)` (only reads a single property).
- Add tests to verify DGP's CC inputs.
- Add Kotlin JVM test project.

fix #4467

### CODE REVIEW

File: dokka-integration-tests/gradle/src/testExampleProjects/kotlin/ExampleProjectsTest.kt
Comment (CristianGM) [inline dokka-integration-tests/gradle/src/testExampleProjects/kotlin/ExampleProjectsTest.kt:481]: you'll need to add `-Pwhatever=true` to see no one is reading it.

File: dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt [hunk 1]
```diff
@@ -338,7 +337,7 @@ constructor(
                         // (Because org.gradle.testfixtures.ProjectBuilder doesn't support mocking Gradle properties.
                         // But maybe soon! https://github.com/gradle/gradle/pull/30002)
                         project
-                            .provider { project.extra.properties[flag]?.toString() }
+                            .provider { project.findProperty(flag)?.toString() }
```
Comment (adam-enko) [inline dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt:340]: This change is the key fix in this PR.

**Comment by adam-enko** [comment]
GitHub Actions performance is degraded :/
https://www.githubstatus.com/incidents/g5gnt5l5hf56

File: dokka-integration-tests/gradle/src/test/kotlin/KotlinJvmIT.kt [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+        project: DokkaGradleProjectRunner,
+    ) {
+        project.runner
+            .addArguments(
+                ":dokkaGenerate",
+                "--build-cache",
+            )
+            .build {
+                withClue("expect dokkaGenerate runs successfully") {
+                    shouldHaveTask(":dokkaGenerate").shouldHaveOutcome(UP_TO_DATE, SUCCESS)
```
Comment (antohaby) [inline dokka-integration-tests/gradle/src/test/kotlin/KotlinJvmIT.kt:34]: is it UP_TO_DATE or SUCCESS? 
why cant it be just one particular state?  e.g. SUCCESS on first run, UP_TO_DATE on second?

File: dokka-integration-tests/gradle/src/test/kotlin/KotlinMultiplatformIT.kt [hunk 3]
```diff
@@ -186,4 +171,53 @@ class KotlinMultiplatformIT {
...
+                shouldHaveTask(":dokkaGenerate").shouldHaveOutcome(UP_TO_DATE, SUCCESS)
+
+                output shouldContain "Configuration cache entry stored"
+
+                testConfigurationCacheResult(project, testedVersions)
+            }
+        }
+
+        withClue("second build - because sometimes KGP needs to finish installing kotlin-native-prebuilt") {
+            // without this second build the test fails on TeamCity, because the CC entry isn't reused because of:
```
Comment (antohaby) [inline dokka-integration-tests/gradle/src/test/kotlin/KotlinMultiplatformIT.kt:203]: is it happening on older kotlin versions only?

File: dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt (hunk 1 above)
Comment (antohaby) [reply dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt:340]: Why not ProvidersFactory.gradleProperty() ? 

i think gradle suggests this as "recommended" https://docs.gradle.org/current/javadoc/org/gradle/api/provider/ProviderFactory.html#gradleProperty(java.lang.String)

Comment (antohaby) [reply dokka-runners/dokka-gradle-plugin/src/main/kotlin/internal/PluginFeaturesService.kt:340]: ah, I see above you're already using it. and this part is for unit tests. my bad :/

File: dokka-integration-tests/gradle/src/test/kotlin/KotlinJvmIT.kt (hunk 2 above)
Comment (adam-enko) [reply dokka-integration-tests/gradle/src/test/kotlin/KotlinJvmIT.kt:34]: The tests run in a stable directory in the project's `build/` directory (for easier checking, and to catch caching issues.) This means if a test re-runs the tasks could be up-to-date.

File: dokka-integration-tests/gradle/src/test/kotlin/KotlinMultiplatformIT.kt (hunk 3 above)
Comment (adam-enko) [reply dokka-integration-tests/gradle/src/test/kotlin/KotlinMultiplatformIT.kt:203]: I think it's something that was introduced in newer versions, due to kotlin-native-prebuilt changes.
