### PR TITLE
Fix source links to accessors in the KotlinAsJava plugin

### LINKED ISSUE #3367: [K2] Missed source link for generated getter/setter in kotlin-as-java output
```Kotlin
class DefValue(val str: String = "defString")
```

Setup source linking and apply `kotlin-as-java` Dokka plugin.

Output in K1 for getter method will have source link
image

and for K2 it missed:

image

**Installation**
- Dokka version: 1.9.20

Parent: #3328

### PR DESCRIPTION
**Pull request by vmishenev**
fixes #3367

### CODE REVIEW

File: dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt [hunk 1]
```diff
@@ -926,7 +926,14 @@ internal class DokkaSymbolVisitor(
         else -> false
     }
 
-    private fun KaSymbol.getSource() = KtPsiDocumentableSource(psi).toSourceSetDependent()
+    private fun KaSession.getSource(symbol: KaSymbol): SourceSetDependent<DocumentableSource> {
+        val psi = when(symbol) {
+            // implicit/default accessors have no psi
+            is KaPropertyAccessorSymbol -> symbol.containingSymbol?.psi
```
Comment (vmishenev) [inline dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt:949]: Also, see an internal discussion in AA.

In the case of generated declarations, it returns PSI of the declaration from which this (synthetic) declaration is derived.

File: dokka-subprojects/plugin-base/src/test/kotlin/transformers/SourceLinkTransformerTest.kt [hunk 2]
```diff
@@ -128,4 +128,48 @@ class SourceLinkTransformerTest : BaseAbstractTest() {
             }
         }
     }
+
+    @Test
+    fun `synthetic enum values should have source link`() {
```
Comment (vmishenev) [inline dokka-subprojects/plugin-base/src/test/kotlin/transformers/SourceLinkTransformerTest.kt:223]: This test is not affected by this change. 
It has been added JIC

File: dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt (hunk 1 above)
Comment (whyoleg) [reply dokka-subprojects/analysis-kotlin-symbols/src/main/kotlin/org/jetbrains/dokka/analysis/kotlin/symbols/translators/DefaultSymbolToDocumentableTranslator.kt:949]: [(internal discussion)](https://jetbrains.slack.com/archives/C061DS4G41J/p1765816953256829)
