### PR TITLE
Fix inconsistent flow for `B, Strong, Em, I` tags, add support `<h4-6>` javadoc html tags

### LINKED ISSUE #4373: Incorrect flow for `<b> <strong> <em>` Javadoc html tags, no support for `<h4> <h5> <h6>`
1. **Fix incorrect flow for Bold and Strong tags**
KDoc currently renders Strong as` MarkdownElementTypes.STRONG->B(DocTag)->TextStyle.Strong`, but should be `MarkdownElementTypes.STRONG->Strong(DocTag)->TextStyle.Strong`
Html tags `<b>` and `<strong>` from Javadoc are rendered as:
`<b>->B->TextStyle.Strong`, should be `<b>->B->TextStyle.Bold`
`<strong>->Strong->nowhere`, should be `<strong>->Strong->TextStyle.Strong`
2. **`<em> `html tag from Javadoc is converted in [HtmlToDocTagConverter.kt](https://github.com/Kotlin/dokka/blob/c6db331ed4fd32654e406fd6b7e37c67e76a0fa4/dokka-subprojects/analysis-java-psi/src/main/kotlin/org/jetbrains/dokka/analysis/java/parsers/doctag/HtmlToDocTagConverter.kt#L56) to Em on Documentables model, but is not converted further to Pages. New `TextStyle.Emphasis` is needed to be created.
Additionally,  [MarkdownElementTypes.EMPH-> I(children, params)](https://github.com/Kotlin/dokka/blob/c6db331ed4fd32654e406fd6b7e37c67e76a0fa4/dokka-subprojects/analysis-markdown-jb/src/main/kotlin/org/jetbrains/dokka/analysis/markdown/jb/factories/DocTagsFromIElementFactory.kt#L38) should now be converted to Em DocTag and further into TextStyle.Emphasis.**
3. **Add support for remaining header html tags `<h4-6>`.**

Related: https://github.com/Kotlin/dokka/issues/2262

### PR DESCRIPTION
**Pull request by yuriioliinyk4**
Fix #4373

### CODE REVIEW

File: dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/pages/ContentNodes.kt [hunk 1]
```diff
@@ -391,7 +391,7 @@ public enum class TokenStyle : Style {
 }
 
 public enum class TextStyle : Style {
-    Bold, Italic, Strong, Strikethrough, Paragraph,
+    Bold, Italic, Strong, Emphasis, Strikethrough, Paragraph,
```
Comment (whyoleg) [inline dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/pages/ContentNodes.kt]: I think we should add new enum entries only at the end, so as to keep the `ordinal` of other entries unchanged?

File: dokka-subprojects/plugin-base/src/test/kotlin/parsers/JavadocParserTest.kt [hunk 2]
```diff
@@ -457,13 +475,13 @@ class JavadocParserTest : BaseAbstractTest() {
     }
 
     @Test
-    fun `u tag is handled properly`() {
+    fun `u and em tags are handled properly`() {
```
Comment (whyoleg) [inline dokka-subprojects/plugin-base/src/test/kotlin/parsers/JavadocParserTest.kt]: I think it makes sense to have separate tests for separate tags (as with other tags in the file)

Comment (yuriioliinyk4) [reply dokka-subprojects/plugin-base/src/test/kotlin/parsers/JavadocParserTest.kt]: done. Additionally, I have added helper method `testHtmlTags` and use it to simplify several tests for html tags, since there was repeated logic.

File: dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/pages/ContentNodes.kt (hunk 1 above)
Comment (yuriioliinyk4) [reply dokka-subprojects/core/src/main/kotlin/org/jetbrains/dokka/pages/ContentNodes.kt]: updated
