### PR TITLE
Filter out JVM mapped properties

### LINKED ISSUE #3939: [K2] Inherited properties are missed
In Dackka, the following test
```kt
@Test
fun `Externally-inherited vars from Kotlin source`() {
    val module =
        """
        |class Test {
        |   class Child: kotlin.RuntimeException()
        |}
    """
            .render()

    // kotlin.Throwable is an `actual typealias`.
    val throwableDRI = "kotlin.Throwable"
    // add/get is not consolidated into a property in Kotlin
    val sixFuns =
        listOf(
            "addSuppressed",
            "getSuppressed",
            "fillInStackTrace",
            "printStackTrace",
            "getLocalizedMessage",
            "initCause",
        )
    // "Message" becomes a "val" in Kotlin, which hides its getter. ToString is from Object.
    // val missingInKotlin = listOf("getMessage", "toString")
    // TODO: figure out why stackTrace is accessors in Kotlin (but a field in Java) upstream
    // Maybe inherited accessors don't get merged into a property? Cause/stackTrace are
    // private fields upstream, as is `*final* String detailMessage`....
    val stackTraceAccessors = listOf("getStackTrace", "setStackTrace")
    val printOverloads = listOf("printStackTrace", "printStackTrace")
    val expectedProps = listOf("cause", "message")
    val expectedPropAccessors = listOf("getCause", "getMessage")
    val expectedFuns = sixFuns + printOverloads + stackTraceAccessors

    // This is a test of the upstream dokka Documentables tree
    val dChild = module.explicitClasslike("Child")
    assertThat(dChild.properties.size).isEqualTo(2)
    assertThat(dChild.functions.size).isEqualTo(10)
    assertThat(dChild.properties.names()).containsExactlyElementsIn(expectedProps)
    assertThat(dChild.functions.names()).containsExactlyElementsIn(expectedFuns)

    val dMessageProp = dChild.properties.single { it.name == "message" }
    val dGetStackTrace = dChild.functions.single { it.name == "getStackTrace" }
    assertThat(dMessageProp.dri.fullName).contains(throwableDRI)
    assertThat(dMessageProp.getter!!.dri.fullName).contains(throwableDRI)
    assertThat(dGetStackTrace.dri.fullName).contains(throwableDRI)

    // This is a test of the dackka Components tree
    val childPage = module.page("Child").data.content

    val inheritedFuns = childPage.data.inheritedFunctions.from(throwableDRI)!!.value
    val funNames = inheritedFuns.items().map { it.name() }

    javaOnly {
        assertThat(funNames.size).isEqualTo(12)
        assertThat(funNames).containsExactlyElementsIn(expectedFuns + expectedPropAccessors)

        assertThat(childPage.data.inheritedProperties.items).isEmpty()
    }
    kotlinOnly {
        assertThat(funNames.size).isEqualTo(10)
        assertThat(funNames).containsExactlyElementsIn(expectedFuns)

        val inheritedProps = childPage.data.inheritedProperties.from(throwableDRI)!!.value
        val propNames = inheritedProps.items().map { it.name() }
        assertThat(propNames.size).isEqualTo(2)
        assertThat(propNames).containsExactlyElementsIn(expectedProps)
    }
}
```
and it's failing at `expected: 10 but was : 0`.

### PR DESCRIPTION
**Pull request by vmishenev**
fixes #3939

### CODE REVIEW

File: dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/transformers/documentables/JvmMappedMethodsDocumentableFilterTransformer.kt [hunk 1]
```diff
@@ -256,15 +257,21 @@ internal class JvmMappedMethodsDocumentableFilterTransformer(context: DokkaConte
...
-        if (d is DFunction && d.isOnlyInJVM()) {
-            if (d.hasDeprecated())
-                true
-            else {
-                val fqn = d.dri.let { it.packageName + "." + it.classNames + "." + it.callable?.name }
-                fqn in VISIBLE_METHOD_SIGNATURES || fqn in MUTABLE_METHOD_SIGNATURES || fqn in DEPRECATED_LIST_METHODS || fqn in HIDDEN_METHOD_SIGNATURES || fqn in NOT_CONSIDER_METHOD_SIGNATURES
+        if (d.isOnlyInJVM()) {
+            when (d) {
+                is DFunction -> d.shouldBeSuppressed()
+                is DProperty -> d.getter?.shouldBeSuppressed() ?: false
```
Comment (whyoleg) [inline dokka-subprojects/plugin-base/src/main/kotlin/org/jetbrains/dokka/base/transformers/documentables/JvmMappedMethodsDocumentableFilterTransformer.kt:274]: What about `setter`?
Probably, we don't need to check for it, but it would be nice to have a comment here on why

**Review by whyoleg — APPROVED** [review]
